extends RefCounted
## UI copy only. Locale is never consumed by physics, AI or scoring.
const TEXT := {
"tagline":["DRAW IT. HIDE IT. SMASH YOUR WAY OUT.","직접 그리고, 숨고, 반격하세요."],
"practice":["WORKSHOP · LEARN & TRY YOUR TOY","연습장 · 직접 만든 무기 시험하기"],
"seek_first":["PLAY · SEEK FIRST","게임 시작 · 술래부터"],
"hide_first":["PLAY · HIDE FIRST","게임 시작 · 숨는 역할부터"],
"offline":["1 human + 3 bots · offline · 4 rounds","사람 1명 + 봇 3명 · 오프라인 · 4라운드"],
"field":["FIELD · fight where you are found (8s)","현장 반격 · 발견된 곳에서 8초 교전"],
"classic":["CLASSIC · centre duel (5s)","중앙 결투 · 비교용 5초 모드"],
"compact":["4-player search zone (full maps preserved)","4인용 탐색 구역 사용 (전체 맵은 유지)"],
"settings":["SETTINGS & CONTROLS","설정 및 조작키"],
"quit":["QUIT","게임 종료"],
"make":["MAKE YOUR TOY","나만의 무기 그리기"],
"untimed":["WORKSHOP · NO TIME LIMIT","연습장 · 시간제한 없음"],
"next_toy":["NEXT ROUND · KEEP CREATING","다음 라운드 준비 · 자유롭게 그리세요"],
"live_round":["The current round continues. This toy is for NEXT round only.","현재 경기는 계속됩니다. 이 무기는 다음 라운드에만 적용됩니다."],
"queued":["Next-round sketch kept. You can keep editing.","다음 라운드 그림을 보관했습니다. 계속 수정할 수 있어요."],
"queue":["KEEP FOR NEXT ROUND","다음 라운드에 사용할 그림 보관"],
"spectate":["BACK TO SPECTATING","관전으로 돌아가기"],
"ready":["READY · LET'S PLAY","준비 완료 · 시작"],
"test_toy":["EQUIP & TRY","장착하고 시험하기"],
"undo":["UNDO","되돌리기"],"clear":["CLEAR","지우기"],"grip":["GRIP","잡는 위치"],
"quick":["QUICK · faster / lighter push","빠름 · 빠른 회복 / 작은 넉백"],
"balanced":["BALANCED · all-round toy","균형 · 기본 공격"],
"heavy":["HEAVY · slower / bigger push","무거움 · 느린 회복 / 큰 넉백"],
"fill":["Fill safe outlines (ambiguous holes stay open)","안전한 윤곽 채우기 (모호한 구멍은 유지)"],
"save":["SAVE","저장"],"load":["LOAD","불러오기"],"overwrite":["CONFIRM OVERWRITE","덮어쓰기 확인"],
"confirm_slot":["This slot contains a toy. Press SAVE again to replace it.","이미 그림이 있습니다. 다시 저장을 누르면 교체합니다."],
"saved":["Saved. Previous valid version kept as backup.","저장 완료. 이전 정상본은 백업으로 보관했습니다."],
"recovered":["Recovered the previous valid backup. Please review your toy.","이전 정상 백업을 복구했습니다. 무기 모양을 확인하세요."],
"legacy":["Loaded an older slot. It stays unchanged until you SAVE.","이전 버전의 슬롯을 불러왔습니다. 저장 전까지 원본은 그대로입니다."],
"empty":["Empty or damaged slot. No drawing was replaced.","비었거나 손상된 슬롯입니다. 현재 그림은 유지됩니다."],
"save_error":["Could not save: ","저장하지 못했습니다: "],
"stats":["INK %d%% · REACH %.2fm\n%s · %.2fs attack · %d solid outlines","잉크 %d%% · 사거리 %.2fm\n%s · 공격 %.2f초 · 입체 채움 %d개"],
"room_info":["%d active / %d hideouts · %d × %d m world","활성 은신처 %d / 전체 %d곳 · 전체 %d × %dm"],
"points":["First escape +1 once · Survival +3 · Never found +2","첫 탈출 +1 (1회) · 생존 +3 · 미발각 +2"],
"paused":["PAUSED","일시정지"],
"resume":["RESUME","계속하기"],
"back":["BACK","뒤로"],"title":["BACK TO TITLE","시작 화면으로"],
"comfort_note":["Comfort settings change presentation, never the rules or timers.","편안함 설정은 화면 연출만 바꾸며 판정과 시간은 바꾸지 않습니다."],
"sensitivity":["Mouse sensitivity","마우스 감도"],"fov":["Vertical field of view","세로 시야각"],
"volume":["Effects volume","효과음 음량"],"invert":["Invert mouse Y","마우스 상하 반전"],
"reduced":["Reduced motion","동작 줄이기"],"sway":["Hand sway","손 흔들림"],
"bob":["Walking bob","이동 시 상하 움직임"],"contact":["Contact animation","타격 반동 연출"],
"metrics":["Opt-in local diagnostics (no upload)","로컬 진단 기록 (선택 · 외부 전송 없음)"],
"cues":["Text cues for nearby sounds","주변 소리를 글자로도 알림"],
"remap":["CHANGE KEYS","조작키 변경"],"reset_keys":["RESET DEFAULT KEYS","기본 조작키 복원"],
"key_title":["YOUR CONTROLS","나에게 맞는 조작키"],
"key_note":["Select an action, then press a key or mouse button. Esc cancels.\nEsc / Enter / F11 / F12 are kept for menus and safety.","동작을 고른 뒤 키 또는 마우스 버튼을 누르세요. Esc는 취소입니다.\nEsc / Enter / F11 / F12는 메뉴와 화면 제어용으로 고정됩니다."],
"press_key":["Press a key or mouse button…","키 또는 마우스 버튼을 누르세요…"],
"key_busy":["Already assigned to: ","이미 사용 중인 동작: "],
"key_invalid":["Reserved or unsupported key. Choose another.","고정 또는 지원하지 않는 키입니다. 다른 키를 골라주세요."],
"forward":["Move forward","앞으로"],"backward":["Move backward","뒤로 이동"],
"left":["Move left","왼쪽"],"right":["Move right","오른쪽"],
"attack":["Swing","공격"],"interact":["Inspect / hide","검사 / 숨기"],
"dash":["Dodge","대시"],"quiet":["Quiet movement","조용히 이동"],"taunt":["Taunt","도발"],
"map":["Map","지도"],"workshop":["Workshop / next-round drawing","연습 그림판 / 다음 라운드 준비"],
"seeker":["SEEKER","술래"],"hider":["HIDER","숨는 역할"],
"hidden":["HIDDEN · [%s] LEAVE","은신 중 · [%s] 나오기"],
"inspect":["[%s] INSPECT","[%s] 검사하기"],"hide":["[%s] HIDE","[%s] 숨기"],
"remaining":["%d HIDERS · SCORE %d","남은 하이더 %d명 · 내 점수 %d"],
"dodgeready":["DODGE READY","대시 준비됨"],"dodgewait":["DODGE RECOVERING","대시 회복 중"],
"caught":["CAUGHT · [%s] PREPARE NEXT TOY","포획됨 · [%s] 다음 무기 준비"],
"last_round":["CAUGHT · FINAL ROUND","포획됨 · 마지막 라운드 관전"],
"spectating":["SPECTATING ","관전 중: "],
"training":["PRACTICE · NO SCORE / NO TIMER","연습 · 점수와 시간제한 없음"],
"training_tasks":["%s Equip toy  %s Move  %s Dodge  %s Land 3 hits","%s 무기 장착  %s 이동  %s 대시  %s 3회 명중"],
"training_done":["READY! Test another toy or start a match from the menu.","기본 조작 완료! 다른 무기를 시험하거나 메뉴에서 경기를 시작하세요."],
"training_hits":["HITS %d · BLOCKS %d · MISSES %d","명중 %d · 막힘 %d · 빗나감 %d"],
"training_draw":["[%s] DRAW AGAIN · Esc MENU","[%s] 다시 그리기 · Esc 메뉴"],
"training_hint":["Move close to the pink practice toy and swing.","분홍색 연습 상대 가까이 가서 무기를 휘두르세요."],
"result":["ROUND COMPLETE","라운드 종료"],"complete":["MATCH COMPLETE","경기 종료"],
"continue":["CONTINUE [ENTER]","계속 [ENTER]"],
"round_award":["THIS ROUND %+d  ·  TOTAL %d","이번 라운드 %+d · 총점 %d"],
"never_found":["NEVER FOUND","끝까지 미발각"],"escaped":["COUNTERATTACK SURVIVOR","반격 후 생존"],
"sweep":["ALL CAUGHT","전원 포획"],"survivor":["SURVIVED","생존"],
"map_note":["Public sites only. No hidden opponents are shown.","공개 은신처만 표시합니다. 숨은 상대는 보이지 않습니다."],
"nopeek":["NO PEEKING!","아직 보면 안 돼요!"],
"wait":["Search begins in %02d","%02d초 뒤 탐색 시작"],
"waiting":["The hiders are finding their spots.","다른 참가자들이 숨을 곳을 찾고 있습니다."],
"slot":["Slot %d","슬롯 %d"],
"default_restored":["Default controls restored.","기본 조작키로 복원했습니다."],
"found":["FOUND! SMASH YOUR WAY OUT","발견! 반격해서 빠져나가세요"],
"escape":["ESCAPED! FIND NEW COVER","탈출! 새로운 은신처를 찾으세요"],
"start_seek":["READY OR NOT!","준비됐든 안 됐든, 찾으러 갑니다!"],
"hide_now":["HIDE! CHOOSE YOUR ESCAPE ROUTE","숨으세요! 도주 경로도 생각하세요"],
"empty_prop":["EMPTY... TRY ANOTHER SPOT","비어 있습니다. 다른 곳을 찾아보세요"],
"hear_step":["FOOTSTEPS NEARBY","주변에서 발소리가 들립니다"],
"settings_recovered":["An earlier valid settings backup was recovered. Review your settings.","이전 정상 설정을 복구했습니다. 조작과 설정을 확인하세요."],
"language":["Language","언어"]}
const MAPS := {"toy_home":["Toy House","장난감 집"],"warehouse":["Toy Warehouse","장난감 창고"],"garden":["Secret Garden","비밀 정원"]}
const PHASES := [["TITLE","시작"],["DRAW","그리기"],["HIDE","숨기"],["SEEK","탐색"],["FOUND","발견"],["CHASE","교전"],["RESULT","결과"],["COMPLETE","종료"]]

static func get_text(key: String, language: String) -> String:
	if not TEXT.has(key): return key
	return TEXT[key][1 if language == "ko" else 0]

static func font() -> SystemFont:
	var result := SystemFont.new()
	result.font_names = PackedStringArray(["Malgun Gothic","Apple SD Gothic Neo","Noto Sans CJK KR","Noto Sans KR","Noto Sans","DejaVu Sans"])
	return result
